# Generated by Django 4.2.3 on 2023-07-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('source', models.CharField(choices=[('NF', 'Netflix'), ('AM', 'Amazon Prime'), ('CR', 'Crunchyroll'), ('YT', 'Youtube'), ('DP', 'Disney+'), ('HB', 'HBO'), ('HL', 'Hulu'), ('AP', 'Apple'), ('OT', 'Other')], max_length=2)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
